apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: basicapp-java-quarkus-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: basicapp-java-quarkus-sample
    app.kubernetes.io/part-of: basicapp
  name: basicapp-java-quarkus-sample
  namespace: bentaljaard
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: basicapp-java-quarkus-sample
    weight: 100
status: {}
